version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "5000:5000" # Sesuaikan port sesuai kebutuhan
    restart: always  # Restart otomatis jika container crash
    volumes:
      - .:/app  # Sinkronisasi folder lokal dengan container (opsional)
    environment:
      NODE_ENV: production # Menjalankan aplikasi dalam mode production
    command: ["node", "start.js"] # Perintah untuk menjalankan aplikasi

  setup:
    image: alpine:latest
    container_name: setup
    command: |
      sh -c "
      docker-compose build &&
      docker-compose up
      "
    volumes:
      - .:/app
    working_dir: /app
